services:
  cyan-chat:
    image: ghcr.io/johnnycyan/cyan-chat:latest
    ports:
      - "1535:1535"
    volumes:
      - ./data:/app/data
      - ./src/media:/app/dist/media
    environment:
      - YOUTUBE_WS_HOST=localhost:9905
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-eu-north-1}
    restart: unless-stopped
